version: '3.1'
services:
  chess:
    build: .
    image: progweb/chess:development
    command: npm start
    container_name: progweb_chess
    environment:
      - APP_PORT=4567
    depends_on:
      - mysql
    networks: 
      - progweb
    ports:
      - 4567:4567
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
  mysql:
    container_name: progweb_mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_PORT=3306
    image: mysql:5.6
    networks:
      - progweb
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql

  mysql-web:
    container_name: progweb_mysql_web
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    image: phpmyadmin/phpmyadmin:4.7
    networks:
      - progweb
    ports:
      - 13307:80
    restart: unless-stopped

networks:
  progweb:

volumes:
  mysql-data:
    driver: local